In [1]:
from joblib.numpy_pickle_utils import xrange
from numpy import *

In [2]:
class NeuralNet(object):
    # khởi tạo đối tượng của class NeuralNet
    def __init__(self):
        # tạo ma trận trọng số (3x1) với trọng số random. hàm random.random() return 1 số trong khoảng (0,1)
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function: chuyển hóa kết quá về giữa 0 và 1
    def __sigmoid(self, x):
        s = 1 / (1 + exp(-x))
        print (s)
        return s
    
    # đạo hàm của hàm sigmod với công thức ở dưới, x là ma trận hoặc số
    def __sigmoid_derivative(self, x):
        s = x * (1 - x)
        print (s)
        return s

    # huấn luyện mô hình
    def train(self, inputs, outputs, training_iterations):
        for iteration in xrange(training_iterations):
            output = self.learn(inputs) # trả về output mới
            error = outputs - output # chênh lệch giữa output mới và output test
            # Điều chỉnh lại trọng số theo công thức dưới
            factor = dot(inputs.T, error * self.__sigmoid_derivative(output))
            self.synaptic_weights += factor

    # kết quả mà mô hình tạm tính toán, điều chỉnh dần dần trong hàm train
    def learn(self, inputs):
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


In [3]:
if __name__ == "__main__":
    #Khởi tạo
    neural_network = NeuralNet()

    # Train data
    inputs = array([[0,0,1],
                    [1,1,1],
                    [1,0,1]])
    outputs = array([[0,1,1]]).T

    #Train the neural network: thay đổi số lần train để được kết quả tốt hơn
    neural_network.train(inputs, outputs, 2)

    #test
    test = array([1,1,1])
    res = neural_network.learn(test)
    print(res)

[[0.51819514]
 [0.56253185]
 [0.56162702]]
[[0.24966894]
 [0.24608977]
 [0.24620211]]
[[0.5396715 ]
 [0.65946087]
 [0.63403355]]
[[0.24842617]
 [0.22457223]
 [0.23203501]]
[0.71628035]
[0.71628035]
